name: Compiler CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up environment
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential flex bison # Add other dependencies here
    - name: Build compiler
      run: make -C path/to/compiler
    - name: Run tests
      run: ./path/to/compiler/tests/run_tests.sh # You need to create this or a similar script
    # Add additional steps to check results if necessary
